[build]
  command = "python manage.py collectstatic --noinput"
  publish = "static_collected"
  functions = "netlify/functions"

[build.environment]
  PYTHON_VERSION = "3.8"

[dev]
  command = "python manage.py runserver 0.0.0.0:8000"
  port = 8000
  targetPort = 8000

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self' https:; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://cdnjs.cloudflare.com https://cdn.jsdelivr.net; style-src 'self' 'unsafe-inline' https://cdnjs.cloudflare.com https://fonts.googleapis.com; img-src 'self' data: https:; font-src 'self' https://fonts.gstatic.com https://cdnjs.cloudflare.com; connect-src 'self' https:; frame-src 'self' https:; object-src 'none'"

[images]
  remote_images = ["https://same-assets.com/*"]
